// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BlockTrixUploadsController from "./block_trix_uploads_controller"
application.register("block-trix-uploads", BlockTrixUploadsController)

import CheckLockedScribbleController from "./check_locked_scribble_controller"
application.register("check-locked-scribble", CheckLockedScribbleController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScribbleCompareController from "./scribble_compare_controller"
application.register("scribble-compare", ScribbleCompareController)

import ThemeController from "./theme_controller"
application.register("theme", ThemeController)

import TimezoneController from "./timezone_controller"
application.register("timezone", TimezoneController)

import UniquenessValidationController from "./uniqueness_validation_controller"
application.register("uniqueness-validation", UniquenessValidationController)
