// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BlockTrixUploadsController from "./block_trix_uploads_controller"
application.register("block-trix-uploads", BlockTrixUploadsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TimezoneController from "./timezone_controller"
application.register("timezone", TimezoneController)
